openapi: 3.0.1
info:
  title: API Documentation
  description: Detailed API documentation for Anime Products and Users Management.
  version: 1.0.0

paths:
  /api/products:
    $ref: 'products.doc.yaml#/paths'
  /api/users:
    $ref: 'users.doc.yaml#/paths'