components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier of the product.
        name:
          type: string
          description: The name of the product.
        price:
          type: number
          description: The price of the product.
        description:
          type: string
          description: The description of the product.
      required:
        - name
        - price

paths:
  /api/products:
    get:
      summary: Retrieve all products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: The created product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /api/products/{productId}:
    put:
      summary: Update an existing product
      parameters:
        - in: path
          name: productId
          schema:
            type: string
          required: true
          description: The ID of the product to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: The updated product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    delete:
      summary: Delete an existing product
      parameters:
        - in: path
          name: productId
          schema:
            type: string
          required: true
          description: The ID of the product to delete
      responses:
        '204':
          description: Product deleted successfully
